USE master
GO

CREATE DATABASE Practica_2
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRACTICA_2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\Practica_2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRACTICA_2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\Practica_2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE Practica_2 SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC Practica_2.dbo.sp_fulltext_database @action = 'enable'
end
GO
ALTER DATABASE Practica_2 SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE Practica_2 SET ANSI_NULLS OFF 
GO
ALTER DATABASE Practica_2 SET ANSI_PADDING OFF 
GO
ALTER DATABASE Practica_2 SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE Practica_2 SET ARITHABORT OFF 
GO
ALTER DATABASE Practica_2 SET AUTO_CLOSE OFF 
GO
ALTER DATABASE Practica_2 SET AUTO_SHRINK OFF 
GO
ALTER DATABASE Practica_2 SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE Practica_2 SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE Practica_2 SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE Practica_2 SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE Practica_2 SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE Practica_2 SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE Practica_2 SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE Practica_2 SET  ENABLE_BROKER 
GO
ALTER DATABASE Practica_2 SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE Practica_2 SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE Practica_2 SET TRUSTWORTHY OFF 
GO
ALTER DATABASE Practica_2 SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE Practica_2 SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE Practica_2 SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE Practica_2 SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE Practica_2 SET RECOVERY FULL 
GO
ALTER DATABASE Practica_2 SET  MULTI_USER 
GO
ALTER DATABASE Practica_2 SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE Practica_2 SET DB_CHAINING OFF 
GO
ALTER DATABASE Practica_2 SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE Practica_2 SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE Practica_2 SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'PRACTICA_2', N'ON'
GO
ALTER DATABASE Practica_2 SET QUERY_STORE = OFF
GO
USE Practica_2
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Maestro(
	Id char PRIMARY KEY NOT NULL,
	NombreMaestro varchar(40) NOT NULL,
	PrimerApellido varchar(50) NOT NULL,
	SegundoApellido varchar(50) NOT NULL,
	CedulaProfesional int NOT NULL,
	)


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Chofer(
	Id char PRIMARY KEY NOT NULL,
	NombreChofer varchar(30) NOT NULL,
	PrimerApellido varchar(50) NOT NULL,
	SegundoApellido varchar(50) NOT NULL,
)

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Cita(
	Id char PRIMARY KEY NOT NULL,
	NumeroMedico varchar(10) NOT NULL,
	NumeroPaciente varchar(10) NOT NULL,
	HorarioCita time(6) NOT NULL,
	DiaCita date NOT NULL,
    Ubicacion varchar(30) NOT NULL,
)

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Cliente(
	Id char PRIMARY KEY NOT NULL,
	NumeroPaciente varchar(7) NOT NULL,
	Nombre varchar(50) NOT NULL,
	PrimerApellido varchar(10) NOT NULL,
	SegundoApellido varchar(10) NOT NULL,
	FechaNacimiento date NOT NULL,
	Sexo varchar(1) NOT NULL,
	TelefonoContacto int NOT NULL,
	Edad  AS (datediff(year,FechaNacimiento,getdate())),
)

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Diagnostico(
	Id char PRIMARY KEY NOT NULL,
	FechaCita date NOT NULL,
)

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE FechaDisponible(
	Id char PRIMARY KEY NOT NULL,
	Fecha date NOT NULL,
	)

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Horarios(
	Id char PRIMARY KEY NOT NULL,
	Fecha date NOT NULL,
	HorarioDisponible date NOT NULL,
)
SET ANSI_NULLS ON

GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Medico(
	Id char PRIMARY KEY not null,  
	NombreMedico varchar(40) NOT NULL,
	PrimerApellido varchar(50) NOT NULL,
	SegundoApellido varchar(50) NOT NULL,
	CedulaProfesional int NOT NULL,
)

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Psicologo(
	Id char PRIMARY KEY NOT NULL,
	NombrePsicologo varchar(40) NOT NULL,
	PrimerApellido varchar(50) NOT NULL,
	SegundoApellido varchar(50) NOT NULL,
	CedulaProfesional int NOT NULL,
)

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Secretaria(
	Id char PRIMARY KEY NOT NULL,
	NombreSecretaria varchar(40) NOT NULL,
	PrimerApellido varchar(50) NOT NULL,
	SegundoApellido varchar(50) NOT NULL,
	CedulaProfesional int NOT NULL,
)

CREATE NONCLUSTERED INDEX IDX_Maestro_Id ON Maestro
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IDX_Chofer_Id ON Chofer
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IDX_Cliente_Id ON Cliente
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IDX_Diagnostico_Id ON Diagnostico
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IDX_FechaDisponible_Id ON FechaDisponible
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IDX_Horarios_Id ON Horarios
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IDX_Medico_Id ON Medico
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IDX_Psicologo_Id ON Psicologo
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IDX_Secretaria_Id ON Secretaria
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
USE master
GO
ALTER DATABASE Practica_2 SET  READ_WRITE 
GO
